//! Cross-implementation conformance (AUTH_OPT_IN_PLAN.md §6.3).
//!
//! `TimelessUI.TelemetryAuth` (Elixir) and `timeless-authctl` (Rust) are two
//! independent producers of one token format, reconciled only by this
//! crate's verifier. The fixture pins both: a golden token from each minter,
//! one fixed keypair, one policy. If the verifier changes incompatibly,
//! verification of the goldens fails here; if the Elixir wire construction
//! changes, its own golden test (timeless_ui
//! `test/timeless_ui/telemetry_auth_conformance_test.exs`) fails there; if
//! authctl drifts, the byte-equality assertion below fails.
//!
//! Fixture provenance: seed = 32 bytes of 0x07; the Elixir golden was
//! generated by `TimelessUI.TelemetryAuth.sign_token/3` with the claims in
//! that repo's conformance test; the authctl golden is regenerated (and
//! asserted byte-identical) by this test via `mint_at`.

use axum::body::Body;
use axum::http::{Request, StatusCode};
use axum::routing::{get, post};
use axum::Router;
use timeless_api_common::{protect_router, AuthConfig};
use tower::ServiceExt;

const FIXTURE: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/conformance");
const ISSUED_AT: i64 = 1_754_000_000;
const EXPIRES_AT: i64 = 5_000_000_000;
const JTI: &str = "conformance-fixed-jti";

fn fixture(name: &str) -> String {
    std::fs::read_to_string(format!("{FIXTURE}/{name}"))
        .unwrap_or_else(|error| panic!("read fixture {name}: {error}"))
        .trim()
        .to_owned()
}

async fn assert_token_verifies(token: &str) {
    let config = AuthConfig::enforced(
        "metrics",
        "default",
        format!("{FIXTURE}/policy.json"),
    );
    config.preflight().expect("fixture policy must pass preflight");
    let app = protect_router(
        Router::new()
            .route("/api/v1/query", get(|| async { "read" }))
            .route("/api/v1/flush", post(|| async { "maintenance" })),
        config,
    );
    for (path, method) in [("/api/v1/query", "GET"), ("/api/v1/flush", "POST")] {
        let response = app
            .clone()
            .oneshot(
                Request::builder()
                    .uri(path)
                    .method(method)
                    .header("authorization", format!("Bearer {token}"))
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(
            response.status(),
            StatusCode::OK,
            "{method} {path} must accept the conformance token"
        );
    }
}

#[tokio::test]
async fn elixir_minted_golden_token_verifies() {
    assert_token_verifies(&fixture("elixir-token.txt")).await;
}

#[tokio::test]
async fn authctl_reproduces_its_golden_and_it_verifies() {
    let minted = timeless_authctl::mint_at(
        std::path::Path::new(&format!("{FIXTURE}/seed.key")),
        std::path::Path::new(&format!("{FIXTURE}/policy.json")),
        "conformance",
        "metrics",
        EXPIRES_AT - ISSUED_AT,
        ISSUED_AT,
        JTI,
    )
    .expect("mint against the fixture");
    assert_eq!(
        minted,
        fixture("authctl-token.txt"),
        "authctl wire construction drifted from its committed golden"
    );
    assert_token_verifies(&minted).await;
}
